// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SQTWeb.Models.QTMS;

[Table("COM_Ms_SalesQuotationChargeGroup")]
public partial class COM_Ms_SalesQuotationChargeGroup
{
    [Key]
    [StringLength(50)]
    public string GroupCode { get; set; }

    [StringLength(50)]
    public string GroupName { get; set; }
}