// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SQTWeb.Models.QTMS;

[Table("COM_Ms_UnitOfMeasure")]
public partial class COM_Ms_UnitOfMeasure
{
    [StringLength(50)]
    public string UnitClassCode { get; set; }

    [Key]
    [StringLength(50)]
    public string UnitCode { get; set; }

    [StringLength(250)]
    public string UnitName { get; set; }

    public bool? IsBase { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? FactorToBase { get; set; }

    [StringLength(50)]
    public string Symbol { get; set; }
}