// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SQTWeb.Models.QTMS;

[PrimaryKey("CompanyCode", "QuotationNo")]
[Table("COM_Trs_SalesQuotation")]
public partial class COM_Trs_SalesQuotation
{
    [Key]
    [StringLength(10)]
    public string CompanyCode { get; set; }

    [Key]
    [StringLength(30)]
    public string QuotationNo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? QuotationDate { get; set; }

    /// <summary>
    /// COM_Ms_Status
    /// </summary>
    public int? StatusNo { get; set; }

    /// <summary>
    /// COM_Ms_Status
    /// </summary>
    [StringLength(50)]
    public string StatusName { get; set; }

    [StringLength(10)]
    public string CustomerCode { get; set; }

    [StringLength(250)]
    public string CustomerName { get; set; }

    [StringLength(10)]
    public string CurrencyCode { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? ExchangeRate { get; set; }

    [StringLength(50)]
    public string CustomerContactCode { get; set; }

    public string CustomerContactname { get; set; }

    [StringLength(50)]
    public string PortCode { get; set; }

    [StringLength(250)]
    public string PortName { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? GrandTotalGrossWeightKg { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? GrandTotalVolumeCBM { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? GrandTotalFrieghtAmountDest { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? GrandTotalFrieghtAmountTHB { get; set; }

    [StringLength(50)]
    public string AgentCode { get; set; }

    [StringLength(250)]
    public string AgentName { get; set; }

    [StringLength(250)]
    public string AgentAddress1 { get; set; }

    [StringLength(250)]
    public string AgentAddress2 { get; set; }

    [StringLength(250)]
    public string AgentLocation { get; set; }

    [StringLength(250)]
    public string AdditionalInformation { get; set; }

    [StringLength(50)]
    public string ISODocumentVersionNo { get; set; }

    [StringLength(50)]
    public string CreateBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateDate { get; set; }

    [StringLength(50)]
    public string UpdateBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    public bool? IsVoid { get; set; }

    [StringLength(50)]
    public string VoidBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? VoidDate { get; set; }

    [StringLength(250)]
    public string VoidReason { get; set; }

    [InverseProperty("COM_Trs_SalesQuotation")]
    public virtual ICollection<COM_Trs_SalesQuotationFreightCharge> COM_Trs_SalesQuotationFreightCharges { get; set; } = new List<COM_Trs_SalesQuotationFreightCharge>();

    [InverseProperty("COM_Trs_SalesQuotation")]
    public virtual ICollection<COM_Trs_SalesQuotationShipmentDetail> COM_Trs_SalesQuotationShipmentDetails { get; set; } = new List<COM_Trs_SalesQuotationShipmentDetail>();
}