// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SQTWeb.Models.QTMS;

[PrimaryKey("CompanyCode", "ChargeCode", "LineNo", "TierLineNo")]
[Table("COM_Trs_SalesQuotationFreightChargePriceTier")]
public partial class COM_Trs_SalesQuotationFreightChargePriceTier
{
    [Key]
    [StringLength(10)]
    public string CompanyCode { get; set; }

    [Key]
    [StringLength(50)]
    public string ChargeCode { get; set; }

    [Key]
    public int LineNo { get; set; }

    [Key]
    public int TierLineNo { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? FromValue { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? ToValue { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? UnitPrice { get; set; }
}