// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SQTWeb.Models.QTMS;

[PrimaryKey("CompanyCode", "LineNo")]
[Table("COM_Ms_SalesQuotationCharge")]
public partial class COM_Ms_SalesQuotationCharge
{
    [Key]
    [StringLength(10)]
    public string CompanyCode { get; set; }

    [Key]
    public int LineNo { get; set; }

    [StringLength(50)]
    public string ChargeGroupCode { get; set; }

    [Required]
    [StringLength(50)]
    public string ChargeCode { get; set; }

    [StringLength(50)]
    public string ChargeName { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? MinPrice { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? MaxPrice { get; set; }

    [StringLength(50)]
    public string UnitOfMeasure { get; set; }

    [StringLength(50)]
    public string CurrencyCode { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? ExchangeRate { get; set; }
}