// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SQTWeb.Models.QTMS;

[PrimaryKey("CompanyCode", "QuotationNo", "LineNo")]
[Table("COM_Trs_SalesQuotationFreightCharge")]
public partial class COM_Trs_SalesQuotationFreightCharge
{
    [Key]
    [StringLength(10)]
    public string CompanyCode { get; set; }

    [Key]
    [StringLength(30)]
    public string QuotationNo { get; set; }

    [Key]
    public int LineNo { get; set; }

    [StringLength(50)]
    public string ChargeCode { get; set; }

    [StringLength(50)]
    public string ChargeName { get; set; }

    [StringLength(50)]
    public string ChargeUnit { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? UnitPrice { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? MarginAmount { get; set; }

    [StringLength(50)]
    public string CurrencyCode { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? ExchangeRateToHeader { get; set; }

    [ForeignKey("CompanyCode, QuotationNo")]
    [InverseProperty("COM_Trs_SalesQuotationFreightCharges")]
    public virtual COM_Trs_SalesQuotation COM_Trs_SalesQuotation { get; set; }
}