// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SQTWeb.Models.QTMS;

[PrimaryKey("CompanyCode", "QuotationNo", "LineNo")]
[Table("COM_Trs_SalesQuotationShipmentDetail")]
public partial class COM_Trs_SalesQuotationShipmentDetail
{
    [Key]
    [StringLength(10)]
    public string CompanyCode { get; set; }

    [Key]
    [StringLength(30)]
    public string QuotationNo { get; set; }

    [Key]
    public int LineNo { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? Quantity { get; set; }

    [StringLength(50)]
    public string PackageUnit { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? GrossWeight { get; set; }

    [StringLength(50)]
    public string GrossWeightUnit { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? Length { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? Width { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? Height { get; set; }

    [StringLength(50)]
    public string DimensionUnit { get; set; }

    [Column(TypeName = "decimal(18, 6)")]
    public decimal? TotalVolumeCBM { get; set; }

    [ForeignKey("CompanyCode, QuotationNo")]
    [InverseProperty("COM_Trs_SalesQuotationShipmentDetails")]
    public virtual COM_Trs_SalesQuotation COM_Trs_SalesQuotation { get; set; }
}