// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SQTWeb.Models.QTMS;

public partial class QTMSContext : DbContext
{
    public QTMSContext(DbContextOptions<QTMSContext> options)
        : base(options)
    {
    }

    public virtual DbSet<COM_Ms_SalesQuotationCharge> COM_Ms_SalesQuotationCharges { get; set; }

    public virtual DbSet<COM_Ms_SalesQuotationChargeGroup> COM_Ms_SalesQuotationChargeGroups { get; set; }

    public virtual DbSet<COM_Ms_UnitOfMeasure> COM_Ms_UnitOfMeasures { get; set; }

    public virtual DbSet<COM_Trs_SalesQuotation> COM_Trs_SalesQuotations { get; set; }

    public virtual DbSet<COM_Trs_SalesQuotationFreightCharge> COM_Trs_SalesQuotationFreightCharges { get; set; }

    public virtual DbSet<COM_Trs_SalesQuotationFreightChargePriceTier> COM_Trs_SalesQuotationFreightChargePriceTiers { get; set; }

    public virtual DbSet<COM_Trs_SalesQuotationShipmentDetail> COM_Trs_SalesQuotationShipmentDetails { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<COM_Ms_SalesQuotationCharge>(entity =>
        {
            entity.HasKey(e => new { e.CompanyCode, e.LineNo }).HasName("PK_Ms_SalesQuotationCharge");
        });

        modelBuilder.Entity<COM_Ms_UnitOfMeasure>(entity =>
        {
            entity.HasKey(e => e.UnitCode).IsClustered(false);

            entity.HasIndex(e => e.UnitClassCode, "UX_COM_Ms_UnitOfMeasure_UnitClassCode_Base")
                .IsUnique()
                .HasFilter("([IsBase]=(1))");
        });

        modelBuilder.Entity<COM_Trs_SalesQuotation>(entity =>
        {
            entity.HasKey(e => new { e.CompanyCode, e.QuotationNo }).HasName("PK_Trs_SalesQuotation_1");

            entity.Property(e => e.ExchangeRate).HasDefaultValue(1m, "DF_Trs_SalesQuotation_ExchangeRate");
            entity.Property(e => e.StatusName).HasComment("COM_Ms_Status");
            entity.Property(e => e.StatusNo).HasComment("COM_Ms_Status");
        });

        modelBuilder.Entity<COM_Trs_SalesQuotationFreightCharge>(entity =>
        {
            entity.HasKey(e => new { e.CompanyCode, e.QuotationNo, e.LineNo }).HasName("PK_Trs_SalesQuotationFreightCharge");

            entity.HasOne(d => d.COM_Trs_SalesQuotation).WithMany(p => p.COM_Trs_SalesQuotationFreightCharges).HasConstraintName("FK_Trs_SalesQuotationFreightCharge_Trs_SalesQuotation");
        });

        modelBuilder.Entity<COM_Trs_SalesQuotationFreightChargePriceTier>(entity =>
        {
            entity.HasKey(e => new { e.CompanyCode, e.ChargeCode, e.LineNo, e.TierLineNo }).HasName("PK_Trs_SalesQuotationFreightChargePriceTier");
        });

        modelBuilder.Entity<COM_Trs_SalesQuotationShipmentDetail>(entity =>
        {
            entity.HasKey(e => new { e.CompanyCode, e.QuotationNo, e.LineNo }).HasName("PK_Trs_SalesQuotationShipmentDetail");

            entity.HasOne(d => d.COM_Trs_SalesQuotation).WithMany(p => p.COM_Trs_SalesQuotationShipmentDetails).HasConstraintName("FK_Trs_SalesQuotationShipmentDetail_Trs_SalesQuotation");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}