// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SQTWeb.Models.LMS;

[Keyless]
public partial class COM_View_Agent
{
    [Required]
    [StringLength(10)]
    public string custcode { get; set; }

    [Required]
    [StringLength(10)]
    public string type { get; set; }

    [StringLength(4000)]
    public string custname { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string cust { get; set; }

    [StringLength(100)]
    public string contactn1 { get; set; }

    [StringLength(20)]
    public string phoneno { get; set; }

    [StringLength(20)]
    public string faxno { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? creditday { get; set; }

    [StringLength(100)]
    public string address1 { get; set; }

    [StringLength(100)]
    public string address2 { get; set; }

    [StringLength(50)]
    public string location { get; set; }

    [StringLength(10)]
    public string groupcode { get; set; }

    [Required]
    [StringLength(10)]
    public string custcode_GLO { get; set; }
}