// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SQTWeb.Models.LMS;

[Keyless]
public partial class COM_View_CustomerList
{
    [Required]
    [StringLength(50)]
    public string CompanyCode { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string CustomerCode { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string CustomerName { get; set; }

    [StringLength(163)]
    [Unicode(false)]
    public string Description { get; set; }

    [Required]
    [StringLength(7)]
    [Unicode(false)]
    public string Type { get; set; }

    [StringLength(314)]
    public string Address { get; set; }

    [StringLength(50)]
    public string IDNo { get; set; }

    [StringLength(20)]
    public string Branch { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Telephone { get; set; }

    public bool? StopUse { get; set; }
}