// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SQTWeb.Models.LMS;

public partial class LMSContext : DbContext
{
    public LMSContext(DbContextOptions<LMSContext> options)
        : base(options)
    {
    }

    public virtual DbSet<COM_View_Agent> COM_View_Agents { get; set; }

    public virtual DbSet<COM_View_CustomerList> COM_View_CustomerLists { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<COM_View_Agent>(entity =>
        {
            entity.ToView("COM_View_Agent");
        });

        modelBuilder.Entity<COM_View_CustomerList>(entity =>
        {
            entity.ToView("COM_View_CustomerList");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}