// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SQTWeb.Models.FMS;

[Keyless]
public partial class COM_View_MS_TISI_Currency
{
    public long? Seq { get; set; }

    [Required]
    [StringLength(3)]
    public string CurrencyCode { get; set; }

    [StringLength(150)]
    public string CurrencyName { get; set; }

    [StringLength(500)]
    public string Remark { get; set; }

    [StringLength(156)]
    public string CurrencyDescription { get; set; }
}