// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SQTWeb.Models.FMS;

public partial class FMSContext : DbContext
{
    public FMSContext(DbContextOptions<FMSContext> options)
        : base(options)
    {
    }

    public virtual DbSet<COM_View_MS_TISI_Currency> COM_View_MS_TISI_Currencies { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<COM_View_MS_TISI_Currency>(entity =>
        {
            entity.ToView("COM_View_MS_TISI_Currency");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}