// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SQTWeb.Models.ACMS;

public partial class ACMSContext : DbContext
{
    public ACMSContext(DbContextOptions<ACMSContext> options)
        : base(options)
    {
    }

    public virtual DbSet<SysUser> SysUsers { get; set; }

    public virtual DbSet<ViewUserProfile> ViewUserProfiles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SysUser>(entity =>
        {
            entity.Property(e => e.CreateDate).HasDefaultValueSql("(getdate())", "DF_SysUser_Create Date");
            entity.Property(e => e.CurrentProfileID).HasDefaultValueSql("((-1))", "DF_SysUser_Profile ID");
            entity.Property(e => e.ModifyDate).HasDefaultValueSql("(getdate())", "DF_SysUser_Modified Date");
        });

        modelBuilder.Entity<ViewUserProfile>(entity =>
        {
            entity.ToView("ViewUserProfile");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}