// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SQTWeb.Models.ACMS;

[Table("SysUser")]
public partial class SysUser
{
    [Key]
    [StringLength(50)]
    public string Username { get; set; }

    [Required]
    [StringLength(50)]
    public string Password { get; set; }

    [StringLength(50)]
    public string CurrentProfileID { get; set; }

    [Required]
    [StringLength(255)]
    public string Fullname { get; set; }

    [StringLength(225)]
    public string Company { get; set; }

    [StringLength(50)]
    public string Department { get; set; }

    [StringLength(50)]
    public string TelephoneNo { get; set; }

    [StringLength(50)]
    public string MobileNo { get; set; }

    [StringLength(50)]
    public string ExtNo { get; set; }

    [StringLength(255)]
    public string Email { get; set; }

    [StringLength(50)]
    public string EmployeeID { get; set; }

    [StringLength(50)]
    public string Position { get; set; }

    public bool IsAdminRole { get; set; }

    public bool IsVoid { get; set; }

    [StringLength(50)]
    public string VoidBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? VoidDate { get; set; }

    [StringLength(50)]
    public string CreateBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateDate { get; set; }

    [StringLength(50)]
    public string ModifyBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifyDate { get; set; }

    [StringLength(50)]
    public string SessionID { get; set; }
}