// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SQTWeb.Models.ACMS;

[Keyless]
public partial class ViewUserProfile
{
    [Required]
    [StringLength(50)]
    public string Username { get; set; }

    [StringLength(50)]
    public string AppName { get; set; }

    [Required]
    [StringLength(50)]
    public string ProfileID { get; set; }

    [StringLength(255)]
    public string ProfileName { get; set; }

    public bool? ProfileIsVoid { get; set; }

    [StringLength(50)]
    public string AllowedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? AllowedDate { get; set; }
}