// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SQTWeb.Models.COMMON;

public partial class COM_MS_Company
{
    [Key]
    [StringLength(50)]
    public string CompanyCode { get; set; }

    [Column("Company Name TH")]
    [StringLength(100)]
    public string Company_Name_TH { get; set; }

    [Column("Company Name EN")]
    [StringLength(100)]
    public string Company_Name_EN { get; set; }

    [StringLength(50)]
    public string CommercialRegistrationNo { get; set; }

    [StringLength(10)]
    public string ReferOldStockAwbCode { get; set; }

    [StringLength(100)]
    public string Address1 { get; set; }

    [StringLength(100)]
    public string Address2 { get; set; }

    public bool? HeadOffice { get; set; }

    [StringLength(5)]
    public string Branch { get; set; }

    [StringLength(50)]
    public string TelNo { get; set; }

    [StringLength(50)]
    public string CompanyName_NAV { get; set; }

    [StringLength(50)]
    public string CompanyCode_BBL { get; set; }

    [StringLength(50)]
    public string CompanyCode_ICB { get; set; }

    /// <summary>
    /// รหัสลงทะเบียนการนำส่งข้อมูลภาษีหัก ณ ที่จ่ายระบบ SWC
    /// </summary>
    [StringLength(20)]
    public string WHT_SWC_USER_ID { get; set; }

    [StringLength(50)]
    public string BC365CompanyCode { get; set; }
}