// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SQTWeb.Models.COMMON;

[Table("COM_Sys_SeriesNo")]
public partial class COM_Sys_SeriesNo
{
    [Key]
    public int Id { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    [Required]
    [StringLength(255)]
    public string TableName { get; set; }

    [Required]
    [StringLength(255)]
    public string ColumnName { get; set; }

    [Required]
    [StringLength(100)]
    public string FormatSeriesNo { get; set; }

    [StringLength(50)]
    public string SeriesZeroDigit { get; set; }

    [Required]
    [StringLength(50)]
    public string SeriesCode { get; set; }

    [StringLength(4)]
    public string SeriesYear { get; set; }

    [StringLength(2)]
    public string SeriesMonth { get; set; }

    public int SeriesCount { get; set; }

    [StringLength(50)]
    public string LastedSeriesNo { get; set; }

    [StringLength(50)]
    public string ModifyBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifyDate { get; set; }

    public Guid GenerateGuid { get; set; }
}