// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SQTWeb.Models.COMMON;

[PrimaryKey("SettingCode", "SettingSeq")]
[Table("COM_MS_Setting")]
public partial class COM_MS_Setting
{
    [StringLength(50)]
    public string StatusDocument { get; set; }

    public int? StatusNo { get; set; }

    [Key]
    [StringLength(50)]
    public string SettingCode { get; set; }

    [Key]
    public int SettingSeq { get; set; }

    [StringLength(50)]
    public string SettingValue { get; set; }

    [StringLength(50)]
    public string SettingDescription { get; set; }
}