// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SQTWeb.Models.COMMON;

[PrimaryKey("ValueList", "ValueCode")]
[Table("COM_Sys_ValueList")]
public partial class COM_Sys_ValueList
{
    [Key]
    [StringLength(50)]
    public string ValueList { get; set; }

    [Key]
    [StringLength(50)]
    public string ValueCode { get; set; }

    public int ValueSeq { get; set; }

    [Required]
    [StringLength(50)]
    public string ValueName { get; set; }

    [StringLength(50)]
    public string ValueDescription { get; set; }

    public bool ValueInactive { get; set; }

    public bool? ValueDefault { get; set; }

    [StringLength(50)]
    public string ValueType { get; set; }
}