// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SQTWeb.Models.COMMON;

public partial class COMMONContext : DbContext
{
    public COMMONContext(DbContextOptions<COMMONContext> options)
        : base(options)
    {
    }

    public virtual DbSet<COM_MS_Company> COM_MS_Companies { get; set; }

    public virtual DbSet<COM_MS_Setting> COM_MS_Settings { get; set; }

    public virtual DbSet<COM_Sys_SeriesNo> COM_Sys_SeriesNos { get; set; }

    public virtual DbSet<COM_Sys_ValueList> COM_Sys_ValueLists { get; set; }

    public virtual DbSet<COM_View_MS_TISI_Currency> COM_View_MS_TISI_Currencies { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<COM_MS_Company>(entity =>
        {
            entity.Property(e => e.WHT_SWC_USER_ID).HasComment("รหัสลงทะเบียนการนำส่งข้อมูลภาษีหัก ณ ที่จ่ายระบบ SWC");
        });

        modelBuilder.Entity<COM_MS_Setting>(entity =>
        {
            entity.Property(e => e.StatusDocument).HasDefaultValue("Setting", "DF_COM_MS_Setting_StatusDocument");
            entity.Property(e => e.StatusNo).HasDefaultValue(0, "DF_COM_MS_Setting_StatusNo");
        });

        modelBuilder.Entity<COM_Sys_SeriesNo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_COM_Sys_SeriesNo_1");
        });

        modelBuilder.Entity<COM_View_MS_TISI_Currency>(entity =>
        {
            entity.ToView("COM_View_MS_TISI_Currency");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}